apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: "us-central1-docker.pkg.dev/fluent-webbing-474712-k5/docker-artifacts/flask-demo:latest"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo-service
spec:
  selector:
    app: flask-demo
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP