grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 80
    annotations:
      cloud.google.com/load-balancer-type: "External"
  
  # ✅ SECURE: Use existing secret
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  
  # Optional: Persistence
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"